---
name: Nate Lindsey
description: Personal website
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: njlindsey.github.io
locale: en_GB
---
New Webpage --> [https://www.njlindsey.com](https://www.njlindsey.com/)
