theme: jekyll-theme-minimal
title: Nate J. Lindsey
description: 2015 -            PhD in Geophysics, University of California, Berkeley
2011 - 2012   MSc in Geophysics, University of Edinburgh
2006 - 2010   BS in Interdepartmental Engineering, University of Rochester

Google Scholar
