name: Nate Lindsey
description: Personal website
menu:
 - page: Research
   url: /research
   links:
    - title: "Fiber-Optic Seismology"
      url: "#project-one"
    - title: "Thawing Permafrost"
      url: "#project-two"
    - title: "3-D Magnetotelluric Imaging of Geothermal Systems"
      url: "#project-three"
 - page: Publications
   url: /publications
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Curriculum Vitae
   url: /cv
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
    - title: Positions
      url: "#positions"
    - title: Miscellaneous
      url: "#miscellaneous"
# menu_external:
#  - title: OleVik.me
#    url: "http://olevik.me/"
#  - title: Research Gate
#    url: "https://www.researchgate.net/profile/Ole_Vik"
#  - title: LinkedIn
#    url: "https://no.linkedin.com/in/olehhvik"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: njlindsey.github.io
locale: en_GB
