---
name: Nate Lindsey
description: Personal website
menu_external:
title: cv
url: "https://scholar.google.com/citations?user=_6khFkYAAAAJ&hl=en"
title: Google Scholar
url: "https://scholar.google.com/citations?user=_6khFkYAAAAJ&hl=en"
title: GitHub
url: (assets/njlindsey_CV_oct2017)"
menu:
 - page: News
   url: /news
   links:
    - title: Upcoming
    url: "#upcoming"
    - title: news
    url: "#news"
 - page: Research
   url: /research
   links:
    - title: "Fiber-Optic Seismology"
      url: "#project-one"
    - title: "Thawing Permafrost"
      url: "#project-two"
    - title: "3-D Magnetotelluric Imaging of Geothermal Systems"
      url: "#project-three"
 - page: Publications
   url: /publications
   links:
    - title: Working papers
      url: "#working-papers"
    - title: Published papers
      url: "#published-papers"
 - page: Cool Stuff!
   url: /neat
   links:
    - title: Experience
      url: "#experience"
    - title: Education
      url: "#education"
    - title: Positions
      url: "#positions"
    - title: Miscellaneous
      url: "#miscellaneous"
mathjax: false
markdown: kramdown
encoding: utf-8
baseurl: njlindsey.github.io
locale: en_GB
---

[cv](assets/njlindsey_CV_oct2017)
